export const SET_USER_TOKENS = 'SET_USER_TOKENS';
export const SIGN_IN = 'SIGN_IN';
export const SET_IS_USER_SIGNING_IN = 'SET_IS_USER_SIGNING_IN';
export const SET_IS_USER_SIGNING_UP = 'SET_IS_USER_SIGNING_UP';
export const SIGN_OUT = 'SIGN_OUT';
export const RESET_PASSWORD = 'RESET_PASSWORD';
