export const SET_IS_CREATING_DATASET = 'SET_IS_CREATING_DATASET';
export const SET_DATASET_CREATE_ERROR = 'SET_DATASET_CREATE_ERROR';
export const SET_DATASET_CREATE_SUCCESS = 'SET_DATASET_CREATE_SUCCESS';
export const DATASETS_CREATE = 'DATASETS_CREATE';
export const SET_DATASETS_REFRESHING = 'SET_DATASETS_REFRESHING';
