export const SET_IS_CREATING_ENTITY = 'SET_IS_CREATING_ENTITY';
export const SET_ENTITY_CREATE_ERROR = 'SET_ENTITY_CREATE_ERROR';
export const SET_ENTITY_CREATE_SUCCESS = 'SET_ENTITY_CREATE_SUCCESS';
export const ENTITIES_CREATE = 'ENTITIES_CREATE';
export const SET_ENTITY_REFRESHING = 'SET_ENTITY_REFRESHING';
export const ADD_RELATIONSHIP_ENTITY_ID = 'ADD_RELATIONSHIP_ENTITY_ID';
